spring:
  # basic
  application:
    name: "SocialMedia"
  # mongodb
  data:
    mongodb:
      uri: "mongodb://social-media-cosmos-mongo:9UcSfM5HyVkDKU9zCtFN3SLih1vhhWr9Iie2RmPqcymX9Tr9TLFwXuK7rAVUjep9yYuGpmCWWnRnACDbtMVYjg==@social-media-cosmos-mongo.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@social-media-cosmos-mongo@" # mongodb://localhost:27017
      database: "my-social-media"
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  # azure blob
  cloud:
    azure:
      storage:
        blob:
          account-name: "myappsocialmediastorage"
          account-key: "oLf39h+MuzrCIYwx7rNpnQJI98JHZVEabBqae20J4g332//va/2jvUpl/Lp4jTmaeorhprZaOPRZ+AStmcJf8A=="
          endpoint: "https://myappsocialmediastorage.blob.core.windows.net/"

server:
  port: 8080

azure:
  communication:
    connection-string: "endpoint=https://social-media-communication.unitedstates.communication.azure.com/;accesskey=7nWIRT0fnwOiTtrcT0HXfEJAOYSHI5B8LoBumamq+X5O1ZiVlPMUuLR2zK989c4MvE2Ar+5OiXDL2u7UgD6bmw=="
    email:
      sender-address: "DoNotReply@c4908098-8fc2-4bc0-b098-96166c28de5c.azurecomm.net"
      sender-name: "My Social Media"

frontend:
  url: "https://red-moss-07a653b0f.5.azurestaticapps.net" # "http://localhost:3000"
